### ISSUE TITLE
Termux-gui-view broken

### ISSUE THREAD

**Issue by rihaq** [tareksander/termux-gui-package#8]
```
xception in thread Thread-1 (display):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/bin/termux-gui-view", line 48, in display
    for frame in range(0, img.n_frames):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/PIL/Image.py", line 519, in __getattr__
    raise AttributeError(name)
AttributeError: n_frames
```
Maybe because of Pillow?

**Comment by tareksander** [comment]
What type of file did you try to open?

**Comment by tareksander** [comment]
I forgot to check if n_frames is defined for an image, I only checked GIFs with Pillow.

**Comment by rihaq** [comment]
> What type of file did you try to open?

jpg/png

**Comment by rihaq** [comment]
> I forgot to check if n_frames is defined for an image, I only checked GIFs with Pillow.

Please fix

**Comment by tareksander** [comment]
If you want it fixed fast and not wait for the update to get packaged you can try editing the script in $PREFIX/termux-gui-view and replace ````img.n_frames```` on line 48 with ````getattr(img, "n_frames", 1)````, that may work.

**Comment by rihaq** [comment]
Thank you fixed
